// generated by Fast Light User Interface Designer (fluid) version 1.0104

#include "fl_oyranos.h"

Fl_Group *order_gruppe=(Fl_Group *)0;

Fl_Double_Window* voreinstellungen() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(377, 206, "Einstellungen");
    w = o;
    o->color(FL_BACKGROUND2_COLOR);
    { Fl_Tabs* o = new Fl_Tabs(0, 0, 375, 205, "Einstellungen");
      o->color(FL_BACKGROUND2_COLOR);
      o->align(FL_ALIGN_TOP|FL_ALIGN_INSIDE);
      { Fl_Group* o = new Fl_Group(0, 25, 375, 180, "Colour Profiles");
        o->color(FL_BACKGROUND2_COLOR);
        o->selection_color(FL_BACKGROUND2_COLOR);
        o->labelcolor(FL_FOREGROUND_COLOR);
        { Fl_Group* o = order_gruppe = new Fl_Group(5, 30, 365, 115);
          o->box(FL_ENGRAVED_FRAME);
          o->color(FL_BACKGROUND2_COLOR);
          { Fl_Output* o = new Fl_Output(80, 35, 285, 70, "Pfade:");
            o->type(12);
            o->align(68);
          }
          { Fl_Button* o = new Fl_Button(80, 105, 75, 30, "L\366schen");
            o->color(FL_BACKGROUND2_COLOR);
          }
          { Fl_Button* o = new Fl_Button(160, 105, 85, 30, "Auffrischen");
            o->color(FL_BACKGROUND2_COLOR);
          }
          { Fl_Button* o = new Fl_Button(280, 105, 85, 30, "Neu");
            o->color(FL_BACKGROUND2_COLOR);
          }
          o->end();
        }
        o->end();
        Fl_Group::current()->resizable(o);
      }
      o->end();
      Fl_Group::current()->resizable(o);
    }
    o->show();
    o->end();
  }
  return w;
}
