// generated by Fast Light User Interface Designer (fluid) version 1.0104

#ifndef fl_oyranos_h
#define fl_oyranos_h
#include <FL/Fl.H>
#include "icc_betrachter.h"
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Group.H>
extern Fl_Group *order_gruppe;
#include <FL/Fl_Button.H>
extern TagTexts *fl_oyanos_pfade_browser;
Fl_Double_Window* voreinstellungen_intern();
void oyranos_pfade_waehlen();
#endif
