// generated by Fast Light User Interface Designer (fluid) version 1.0107

#include <libintl.h>
#include "fl_oyranos.h"
#include <string>
#include "icc_oyranos.h"

Fl_Group *order_gruppe=(Fl_Group *)0;

static void cb_Erase(Fl_Button*, void*) {
  oyranos_pfade_loeschen();
}

static void cb_Refresh(Fl_Button*, void*) {
  oyranos_pfade_einlesen();
}

static void cb_New(Fl_Button*, void*) {
  oyranos_pfade_waehlen();
}

TagTexts *fl_oyanos_pfade_browser=(TagTexts *)0;

Fl_Double_Window* voreinstellungen_intern() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(375, 205, _("Preferences"));
    w = o;
    { Fl_Tabs* o = new Fl_Tabs(0, 0, 375, 205, _("Preferences"));
      o->align(FL_ALIGN_TOP|FL_ALIGN_INSIDE);
      { Fl_Group* o = new Fl_Group(0, 25, 375, 180, _("ICC Profiles"));
        { Fl_Group* o = order_gruppe = new Fl_Group(5, 30, 365, 115);
          o->box(FL_ENGRAVED_FRAME);
          { Fl_Button* o = new Fl_Button(80, 105, 75, 30, _("Erase"));
            o->callback((Fl_Callback*)cb_Erase);
          }
          { Fl_Button* o = new Fl_Button(160, 105, 85, 30, _("Refresh"));
            o->callback((Fl_Callback*)cb_Refresh);
          }
          { Fl_Button* o = new Fl_Button(280, 105, 85, 30, _("New"));
            o->callback((Fl_Callback*)cb_New);
          }
          { TagTexts* o = fl_oyanos_pfade_browser = new TagTexts(80, 35, 285, 70, _("Paths:"));
            o->box(FL_NO_BOX);
            o->color(FL_BACKGROUND2_COLOR);
            o->selection_color(FL_SELECTION_COLOR);
            o->labeltype(FL_NORMAL_LABEL);
            o->labelfont(0);
            o->labelsize(14);
            o->labelcolor(FL_FOREGROUND_COLOR);
            o->align(FL_ALIGN_LEFT);
            o->when(FL_WHEN_RELEASE_ALWAYS);
          }
          o->end();
        }
        o->end();
        Fl_Group::current()->resizable(o);
      }
      o->end();
      Fl_Group::current()->resizable(o);
    }
    o->show();
    o->end();
  }
  return w;
}

void oyranos_pfade_waehlen() {
  std::string text;
  text.append ("Hallo\nHallo",11);

    fl_oyanos_pfade_browser->add( text.c_str(), 0);


      fl_oyanos_pfade_browser->topline(0);
      fl_oyanos_pfade_browser->textfont(FL_COURIER);
      fl_oyanos_pfade_browser->textsize(14);
}
