// generated by Fast Light User Interface Designer (fluid) version 1.0104

#ifndef horseshoe_h
#define horseshoe_h
#include <FL/Fl.H>
#include <FL/fl_draw.H>
#include <stdio.h>
#include <stdlib.h>
 #include <iostream>
 #include <sstream>
 using namespace std;
#include <FL/Fl_Double_Window.H>
extern "C" { int main(); }

class ShoeClass : public Fl_Widget {
public:
  ShoeClass(int X,int Y,int W,int H) ;
  ~ShoeClass();
  void draw();
};
#endif
