// generated by Fast Light User Interface Designer (fluid) version 1.0104

#include "horseshoe.h"
#define DBG //cout << __FILE__<<":"<<__LINE__ <<" "<< __func__ << "()" << endl;
#include "icc_draw.h"

int main() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(670, 655);
    w = o;
    { ShoeClass* o = new ShoeClass(0, 0, 670, 655);
      o->box(FL_NO_BOX);
      o->color(FL_BACKGROUND_COLOR);
      o->selection_color(FL_BACKGROUND_COLOR);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelsize(14);
      o->labelcolor(FL_BLACK);
      o->align(FL_ALIGN_CENTER);
      o->when(FL_WHEN_RELEASE);
    }
    o->end();
    o->resizable(o);
  }
  //w->end();
  w->show();

  return Fl::run();
}

ShoeClass::ShoeClass(int X,int Y,int W,int H) : Fl_Widget(X,Y,W,H) {
  DBG
}

ShoeClass::~ShoeClass() {
  DBG
}

void ShoeClass::draw() {
  /*fl_clip(x(),y(),w(),h());
  fl_color(FL_DARK3);
  fl_rectf(x(),y(),w(),h());
  fl_line(10, 30, 300, 300);
    fl_color(FL_BLACK);
    fl_begin_line();
    fl_vertex(12,20);
    fl_vertex(40,10);
    fl_vertex(300,280);
    fl_vertex(30,140);
    fl_end_line();

  fl_pop_clip();*/
  draw_cie_shoe(x(), y(), w(), h());
  DBG
}
