#ifndef ICC_VERSION_H
#define ICC_VERSION_H

#define ICC_EXAMIN_VERSION_A 0
#define ICC_EXAMIN_VERSION_B 3
#define ICC_EXAMIN_VERSION_C 8
#define ICC_EXAMIN_VERSION 0.38
#define ICC_EXAMIN_V 0.38
#define ICC_EXAMIN_D _("May 2004 - September 2005")

#endif //ICC_VERSION_H
