#ifndef ICC_VERSION_H
#define ICC_VERSION_H

#define ICC_EXAMIN_VERSION_A 0
#define ICC_EXAMIN_VERSION_B 3
#define ICC_EXAMIN_VERSION_C 3
#define ICC_EXAMIN_VERSION 0.33
#define ICC_EXAMIN_V 0.33
#define ICC_EXAMIN_D _("Mai 2004 - Mai 2005")

#endif //ICC_VERSION_H
