#ifndef ICC_VERSION_H
#define ICC_VERSION_H

#define ICC_EXAMIN_VERSION_A 0
#define ICC_EXAMIN_VERSION_B 4
#define ICC_EXAMIN_VERSION_C 5
#define ICC_EXAMIN_VERSION 405
#define ICC_EXAMIN_V "0.45"
#define ICC_EXAMIN_D _("May 2004 - September 2007")
#define ICC_CINEPAINT_VERSION "Gtk CinePaint 0.23-0"

#endif //ICC_VERSION_H
