#ifndef ICC_VERSION_H
#define ICC_VERSION_H

#define ICC_EXAMIN_VERSION_A 0
#define ICC_EXAMIN_VERSION_B 4
#define ICC_EXAMIN_VERSION_C 4
#define ICC_EXAMIN_VERSION 404
#define ICC_EXAMIN_V "0.44"
#define ICC_EXAMIN_D _("May 2004 - September 2007")

#endif //ICC_VERSION_H
