#ifndef ICC_VERSION_H
#define ICC_VERSION_H

#define ICC_EXAMIN_VERSION_A 0
#define ICC_EXAMIN_VERSION_B 3
#define ICC_EXAMIN_VERSION_C 7
#define ICC_EXAMIN_VERSION 0.37
#define ICC_EXAMIN_V 0.37
#define ICC_EXAMIN_D _("May 2004 - Aug 2005")

#endif //ICC_VERSION_H
