// Author:    Kai-Uwe Behrmann
// Copyright: Kai-Uwe Behrmann <ku.b@gmx.de>
// Date:      14. 09. 2004


#include "icc_examin.h"
#include "icc_ueber.h"

#define DEBUG_ICCUEBER

std::string
getUeberHtml()
{
 DBG_PROG_START
  char SF[] = "#cccccc";  // Standard hintergrundFarbe
  char HF[] = "#aaaaaa";  // Hervorgehoben
  #define LAYOUTFARBE if (layout[l++] == true) \
                        html << HF; \
                      else \
                        html << SF; //Farbe nach Layoutoption auswählen
  int l = 0;
  std::stringstream html;


  html << "<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">";
  html << "<html><head>" << endl;
  html << "<title>" << _("Über ICC_Examin") << "</title>\n";
  html << "<meta http-equiv=\"content-type\" content=\"text/html; charset=ISO-8859-1\">" << endl;
  html << "<meta name=\"description\" content=\"icc_examin ICC Profil Betrachter\">\n";
  html << "<meta name=\"author\" content=\"automatic generated by icc_examin-" << ICC_EXAMIN_V << "\">\n";
  html << "</head><body bgcolor=\"" << SF << "\">" << endl << endl;

  // Allgemeine Informationen
    html << "<h2>";
    html << "Hallo";
    html << "</h2>";
    html <<     "<br>\n\n";
  DBG_PROG

  html <<       "<table align=left cellpadding=\"2\" cellspacing=\"0\" border=\"0\" width=\"90%\" bgcolor=\"" << SF << "\">\n";
  html <<       "<thead> \n";
  html <<       "  <tr> \n"; DBG
  // Tabellenkopf
  int s = 0;           // Spalten
  int f = 0;           // Spalten für Farben
  DBG_PROG
  l = 0;
  for (s = 0; s < 1; s++) {
    if (s < f) {
      if (s == 0) {
        html <<   "    <th width=\"25\">" << _("Messfarbe") << "</th>";
      } else {
        html <<   "    <th width=\"25\">" << _("Profilfarbe") << "</th>";
      }
    }
  } DBG_PROG
  html <<       "  </tr>\n";
  html <<       "</thead>\n<tbody>\n";

  html <<       "</tbody>\n</table>\n\n<br>\n</body></html>\n";
  //DBG_NUM_S(html.str() )
  DBG_PROG_ENDE
  return html.str();
}

