// generated by Fast Light User Interface Designer (fluid) version 1.0104

#include "neu.h"
#include "icc_draw.h"
#include "icc_utils.h"
using namespace std;

static int main() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(340, 248);
    w = o;
    { ShoeClass* o = new ShoeClass(5, 5, 330, 235);
      o->box(FL_NO_BOX);
      o->color(FL_BACKGROUND_COLOR);
      o->selection_color(FL_BACKGROUND_COLOR);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelfont(0);
      o->labelsize(14);
      o->labelcolor(FL_BLACK);
      o->align(FL_ALIGN_CENTER);
      o->when(FL_WHEN_RELEASE);
    }
    o->end();
  }
  w->show();
  { Fl_Window* o = new Fl_Window(100, 100);
    w = o;
    o->when(FL_WHEN_NEVER);
    new Fl_Button(25, 25, 60, 25, "button");
    o->end();
  }
  w->show();
  return Fl::run();
}

ShoeClass::ShoeClass(int X,int Y,int W,int H) : Fl_Widget(X,Y,W,H) {
  DBG
}

ShoeClass::~ShoeClass() {
  DBG
}

void ShoeClass::draw() {
  /*fl_clip(x(),y(),w(),h());
  fl_color(FL_DARK3);
  fl_rectf(x(),y(),w(),h());
  fl_line(10, 30, 300, 300);
    fl_color(FL_BLACK);
    fl_begin_line();
    fl_vertex(12,20);
    fl_vertex(40,10);
    fl_vertex(300,280);
    fl_vertex(30,140);
    fl_end_line();

  fl_pop_clip();*/
  draw_cie_shoe(x(), y(), w(), h());
  DBG
}
