// generated by Fast Light User Interface Designer (fluid) version 1.0104

#ifndef neu_h
#define neu_h
#include <FL/Fl.H>
#include <FL/fl_draw.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Button.H>

class ShoeClass : public Fl_Widget {
public:
  ShoeClass(int X,int Y,int W,int H) ;
  ~ShoeClass();
  void draw();
};
#endif
