// generated by Fast Light User Interface Designer (fluid) version 1.00

#include <openvrml/gl/viewer.h>
#include <openvrml/vrml97node.h>

using namespace std;

class vFLGLWidget;

class ViewerFLTK : public openvrml::gl::viewer {

public:
  ViewerFLTK(openvrml::browser &,vFLGLWidget* da_widg);
  virtual ~ViewerFLTK();

  void timerUpdate();
  void handleInput( viewer::event_info *e );
  void handleRedraw();
  void vMousePressEvent( int, int, int );
  void vMouseReleaseEvent( int, int, int );
  void vMouseMoveEvent( int, int, int, int );
  void vKeyH();
  unsigned char Hdraw, Hok;
  
protected:

  // Window system specific methods

  virtual void post_redraw();
  virtual void set_cursor( cursor_style c);
  virtual void swap_buffers();
  virtual void set_timer( double );

private:

  int d_width, d_height;
  vFLGLWidget* da_widget;

};

